dev:
  host: ${REMOTE_DEV_HOST}
  user: ${REMOTE_DEV_USER}
  root: ${REMOTE_DEV_ROOT}
  uri: ${REMOTE_DEV_URI}
  paths:
    - files: sites/default/files
  command:
    sql:
      sync:
        options:
          no-dump: true

stage:
  host: ${REMOTE_STAGE_HOST}
  user: ${REMOTE_STAGE_USER}
  root: ${REMOTE_STAGE_ROOT}
  uri: ${REMOTE_STAGE_URI}
  paths:
    - files: sites/default/files
  command:
    sql:
      sync:
        options:
          no-dump: true
