name: ${PROJECT_NAME}
recipe: drupal9
config:
  webroot: docroot
  php: 7.4
  xdebug: false
  drush: '*'
services:
  appserver:
    build_as_root:
      - curl -sL https://deb.nodesource.com/setup_14.x | bash -
      - apt-get install -qq -y nodejs > /dev/null
      - npm install -g gulp-cli > "/dev/null" 2>&1
      - npm install -g yarn > "/dev/null" 2>&1
    environment:
      DRUSH_OPTIONS_ROOT: /app/docroot
      DRUSH_OPTIONS_URI: ${PROJECT_NAME}.lndo.site
      MINK_DRIVER_ARGS: '["chrome", null, "http://chromedriver:4444/wd/hub"]'
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", null, "http://chromedriver:4444/wd/hub"]'
      MINK_DRIVER_CLASS: 'Drupal\FunctionalJavascriptTests\DrupalSelenium2Driver'
      SIMPLETEST_DB: "mysql://drupal:drupal@database/drupal"
      SIMPLETEST_BASE_URL: "https://${PROJECT_NAME}.lndo.site"
      SYMFONY_DEPRECATIONS_HELPER: 'disabled'
      PHP_IDE_CONFIG: "serverName=appserver"
      BEHAT_PARAMS: '{"extensions" : {"Behat\\MinkExtension" : {"base_url" : "http://${PROJECT_NAME}.lndo.site"}, "Drupal\\DrupalExtension" : {"drush" :   {  "root":  "/app/docroot" }}}}'
  chromedriver:
    type: compose
    services:
      image: robcherry/docker-chromedriver:latest
      expose:
        - "4444"
      environment:
        CHROMEDRIVER_WHITELISTED_IPS: ""
        CHROMEDRIVER_URL_BASE: "/wd/hub"
      security_opt:
        - seccomp:unconfined
      command: ["/usr/local/bin/supervisord", "-c", "/etc/supervisord.conf"]
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true
  database:
    type: mariadb:10.4
    creds:
      user: drupal
      password: drupal
      database: drupal
tooling:
  chromedriver:
    service: chromedriver
    description: "Run chromedriver commands."
  behat:
    service: appserver
    description: Run behat tests locally.
    cmd:
      - /app/vendor/bin/behat
  setup:
    service: appserver
    description: Install Drupal.
    cmd:
      - robo setup --load-from $LANDO_MOUNT/.robo/Commands/Drupal/InstallCommand.php --ansi
      - robo build:frontend:reqs --load-from $LANDO_MOUNT/.robo/Commands/Frontend/BuildCommand.php --ansi
      - robo import:config --load-from $LANDO_MOUNT/.robo/Commands/Drupal/ImportConfigCommand.php --ansi
  drupal:update:
    service: appserver
    description: Update Drupal database & configurations
    cmd:
      - robo drupal:update --load-from $LANDO_MOUNT/.robo/Commands/Drupal/DatabaseUpdateCommand.php --ansi
      - robo import:config --load-from $LANDO_MOUNT/.robo/Commands/Drupal/ImportConfigCommand.php --ansi
  sync:all:
    service: appserver
    description: Sync database and files from remote origin
    cmd:
      - robo sync:db --load-from $LANDO_MOUNT/.robo/Commands/Drupal/SyncCommand.php --ansi
      - robo import:config --load-from $LANDO_MOUNT/.robo/Commands/Drupal/ImportConfigCommand.php --ansi
      - robo sync:files --load-from $LANDO_MOUNT/.robo/Commands/Drupal/SyncCommand.php --ansi
  sync:db:
    service: appserver
    description: Sync database from remote origin
    cmd:
      - robo sync:db --load-from $LANDO_MOUNT/.robo/Commands/Drupal/SyncCommand.php --ansi
      - robo import:config --load-from $LANDO_MOUNT/.robo/Commands/Drupal/ImportConfigCommand.php --ansi
  sync:files:
    service: appserver
    description: Sync files from remote origin
    cmd:
      - robo sync:files --load-from $LANDO_MOUNT/.robo/Commands/Drupal/SyncCommand.php --ansi
  validate:all:
    service: appserver
    description: Validating standards on code.
    cmd:
      - robo validate:composer --load-from $LANDO_MOUNT/.robo/Commands/Testing/ValidateCommand.php --ansi
      - robo validate:phpcs:sniff --load-from $LANDO_MOUNT/.robo/Commands/Testing/ValidateCommand.php --ansi
      - robo validate:frontend:src --load-from $LANDO_MOUNT/.robo/Commands/Testing/ValidateCommand.php --ansi
  init:service:search:
    service: appserver
    description: Add Elasticsearch support to the app
    cmd:
      - robo recipes:init:service:search --load-from $LANDO_MOUNT/.robo/Commands/Recipes/SearchServiceCommand.php --ansi
  init:service:cache:
    service: appserver
    description: Add Redis cache support to the app
    cmd:
      - robo recipes:init:service:cache --load-from $LANDO_MOUNT/.robo/Commands/Recipes/CacheServiceCommand.php --ansi
  test:run:all:
    service: appserver
    description: Run behat tests & PHPUnit test locally.
    cmd:
      - robo test:run:phpunit --load-from $LANDO_MOUNT/.robo/Commands/Testing/TestCommand.php --ansi
      - robo test:run:behat --load-from $LANDO_MOUNT/.robo/Commands/Testing/TestCommand.php --ansi
  test:run:behat:
    service: appserver
    description: Run behat tests locally.
    cmd:
      - robo test:run:behat --load-from $LANDO_MOUNT/.robo/Commands/Testing/TestCommand.php --ansi
  test:run:phpunit:
    service: appserver
    description: Run PHPUnit test locally.
    cmd:
      - robo test:run:phpunit --load-from $LANDO_MOUNT/.robo/Commands/Testing/TestCommand.php --ansi
