#!/usr/bin/env bash

set -ev

docroot="$1"
target_branch="$2"

# Prep for Robo commands.
export PATH=$docroot/vendor/bin:$PATH
cd $docroot

yaml-cli get:value robo.yml project.git.remote >> ~/.ssh/known_hosts
robo fetch:remote:branch origin $target_branch
robo deploy

set +v
